Repository unicode-org/icu, pull requests merged in 2018-08, with the labels that each got.

#11 ICU-20033 Add a top-level README.md
  README.md
  tools/images/iculogo_64.png
Labels: enhancement

#14 ICU-20034 Locale assignment operator should set the locale to bogus if OOM occurs.
  icu4c/source/common/locid.cpp
Labels: bug

#15 ICU-20035 UnicodeSet constructors and assignment operator should setToBogus when OOM occurs.
  icu4c/source/common/uniset.cpp
Labels: bug

#8 ICU-13685 c: add @preview (retry)
  icu4c/source/Doxyfile.in
  icu4c/source/common/unicode/icuplug.h
  icu4c/source/common/unicode/utext.h
  icu4c/source/i18n/reldtfmt.h
  icu4c/source/i18n/unicode/decimfmt.h
  icu4c/source/i18n/unicode/smpdtfmt.h
  icu4c/source/i18n/unicode/udat.h
  icu4c/source/i18n/unicode/unum.h
  icu4c/source/i18n/unicode/upluralrules.h
  icu4c/source/layoutex/layout/playout.h
  icu4c/source/layoutex/layout/plruns.h
  icu4c/source/test/intltest/colldata.h
Labels: enhancement

#48 ICU-13530 add UCPTrie/CodePointTrie, switch normalization to use it
  icu4c/source/common/Makefile.in
  icu4c/source/common/common.vcxproj
  icu4c/source/common/common.vcxproj.filters
  icu4c/source/common/common_uwp.vcxproj
  icu4c/source/common/loadednormalizer2impl.cpp
  icu4c/source/common/norm2_nfc_data.h
  icu4c/source/common/normalizer2.cpp
  icu4c/source/common/normalizer2impl.cpp
  icu4c/source/common/normalizer2impl.h
  icu4c/source/common/ucnvsel.cpp
  icu4c/source/common/ucol_swp.cpp
  icu4c/source/common/ucptrie.cpp
  icu4c/source/common/ucptrie_impl.h
  icu4c/source/common/udataswp.h
  icu4c/source/common/umutablecptrie.cpp
  icu4c/source/common/unicode/ucptrie.h
  icu4c/source/common/unicode/umutablecptrie.h
  icu4c/source/common/utrie.h
  icu4c/source/common/utrie2.cpp
  icu4c/source/common/utrie2.h
  icu4c/source/common/utrie2_builder.cpp
  icu4c/source/common/utrie2_impl.h
  icu4c/source/common/utrie_swap.cpp
  icu4c/source/common/uts46.cpp
  icu4c/source/data/in/nfc.nrm
  icu4c/source/data/in/nfkc.nrm
  icu4c/source/data/in/nfkc_cf.nrm
  icu4c/source/data/in/uts46.nrm
  icu4c/source/data/unidata/norm2/uts46.txt
  icu4c/source/i18n/uspoof_impl.h
  icu4c/source/test/cintltst/Makefile.in
  icu4c/source/test/cintltst/cintltst.vcxproj
  icu4c/source/test/cintltst/cintltst.vcxproj.filters
  icu4c/source/test/cintltst/cutiltst.c
  icu4c/source/test/cintltst/trie2test.c
  icu4c/source/test/cintltst/ucptrietest.c
  icu4c/source/test/intltest/tstnorm.cpp
  icu4c/source/test/perf/normperf/Makefile.in
  icu4c/source/test/perf/normperf/simplenormperf.cpp
  icu4c/source/test/testdata/testnorm.txt
  icu4c/source/tools/gennorm2/gennorm2.cpp
  icu4c/source/tools/gennorm2/n2builder.cpp
  icu4c/source/tools/gennorm2/n2builder.h
  icu4c/source/tools/gennorm2/norms.cpp
  icu4c/source/tools/gennorm2/norms.h
  icu4c/source/tools/genrb/parse.cpp
  icu4c/source/tools/toolutil/swapimpl.cpp
  icu4c/source/tools/toolutil/writesrc.cpp
  icu4c/source/tools/toolutil/writesrc.h
  icu4j/main/classes/core/src/com/ibm/icu/impl/ICUBinary.java
  icu4j/main/classes/core/src/com/ibm/icu/impl/Normalizer2Impl.java
  icu4j/main/classes/core/src/com/ibm/icu/impl/UTS46.java
  icu4j/main/classes/core/src/com/ibm/icu/util/CodePointMap.java
  icu4j/main/classes/core/src/com/ibm/icu/util/CodePointTrie.java
  icu4j/main/classes/core/src/com/ibm/icu/util/MutableCodePointTrie.java
  icu4j/main/shared/data/icudata.jar
  icu4j/main/shared/data/icutzdata.jar
  icu4j/main/shared/data/testdata.jar
  icu4j/main/tests/core/src/com/ibm/icu/dev/test/normalizer/BasicTest.java
  icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/CodePointTrieTest.java
Labels: enhancement, question
