Repository unicode-org/icu, pull requests merged in 2018-07, with the labels that each got.

#10 ICU-20032: re-enable Travis and Appveyor config
  .appveyor.yml
  .travis.yml
Labels: enhancement, in progress

#12 ICU-13813: Windows icucheck.bat script does not handle if the tests c…
  icu4c/source/allinone/icucheck.bat
Labels: bug

#13 ICU-10464 Make installation of icu-config optional
  icu4c/source/Makefile.in
  icu4c/source/configure
  icu4c/source/configure.ac
Labels: enhancement
