Repository unicode-org/icu, pull requests merged in 2020-03, with the labels that each got.

#1012 ICU-21003 Fix Git LFS in CI config, add timeout to ICU4J exhaustive test
  .ci-builds/.azure-exhaustive-tests.yml
  .ci-builds/.azure-pipelines.yml
Labels: cherry-pick

#1031 ICU-20965 Remove VS2015 from CI builds, no longer supported by Azure Pipelines [ICU 66]
  .ci-builds/.azure-pipelines.yml
Labels: cherry-pick

#804 ICU-20797 fix UBS compilation error and UBS in test code
  icu4c/source/i18n/collationtailoring.h
  icu4c/source/i18n/numparse_affixes.h
  icu4c/source/test/intltest/numberformattesttuple.cpp
Labels: waiting-on-author

#987 ICU-20956 Fix monetary symbol getters in DecimalFormat
  icu4c/source/i18n/dcfmtsym.cpp
  icu4c/source/i18n/decimfmt.cpp
  icu4c/source/i18n/number_formatimpl.cpp
  icu4c/source/i18n/number_mapper.cpp
  icu4c/source/i18n/number_mapper.h
  icu4c/source/i18n/number_patternmodifier.cpp
  icu4c/source/i18n/number_patternmodifier.h
  icu4c/source/i18n/number_skeletons.cpp
  icu4c/source/i18n/unicode/dcfmtsym.h
  icu4c/source/i18n/unicode/numberformatter.h
  icu4c/source/test/intltest/numbertest_patternmodifier.cpp
  icu4c/source/test/intltest/numfmtst.cpp
  icu4c/source/test/intltest/numfmtst.h
  icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java
  icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java
  icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormatSymbols.java
  icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
Labels: waiting-on-reviewer
